### ISSUE TITLE
MVPs

### ISSUE THREAD

**Issue by simcha-c** [WilfredRuck/Zlack#2]
Hey Wilfred,

Great job on the MVPs :) Here are a few things that should be added/changed. If you think of anything else that you would need to do in order to complete the mvp, please add them! 

- [x] You have chirps in the New account creation :( Please fix that.

**Live Chat**
- [x] Live chat is really part of receiving messages instantly. You should add that to the points of Live chat.

**Channels**
- [x] The first point in channels should be split up into two points. Creating channels should be one point. Joining and leaving a channel should be another.
- [x] Also, a channel can be edited by the creator of that channel. That should be added too.
- [x] Channels can also be private. We should add that to the points.
- [x] with having multiple channels, we're going to need to be able to go btwn channels. That means there needs to be that sidebar that has all the channels there. That should be another point.
- [x] When trying to join a group in slack, theres a component that will show all the public channels that you can join. That should be another point :)

**Direct Messaging**
- [x] this is separate on the sidebar. That should be a separate point.
- [x] You can delete a dm on the sidebar, but those messages persist. meaning, if i delete the dm, but then want to create it again, the messages i sent before will still be there. that should be another point.
- [x] same previous point for team DM's.

Best,
Simcha

**Comment by WilfredRuck** [comment]
Okay, I believe I've properly updated my MVP list to reflect these changes.
